name: simple_interactive_chart
description: "create simple interactive charts with flutter"
version: 0.0.1
homepage: https://github.com/guchengxi1994/chart

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

